# Form implementation generated from reading ui file 'D:\GUI de filtrar\QT_Designer\Columnas_filas.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Col_fil(object):
    def setupUi(self, Col_fil):
        Col_fil.setObjectName("Col_fil")
        Col_fil.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Col_fil)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.Box_col = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Box_col.setGeometry(QtCore.QRect(10, 30, 231, 21))
        self.Box_col.setObjectName("Box_col")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 60, 61, 16))
        self.lineEdit_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.R_si = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.R_si.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.R_si.setObjectName("R_si")
        self.R_no = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.R_no.setGeometry(QtCore.QRect(160, 80, 82, 17))
        self.R_no.setObjectName("R_no")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 110, 71, 16))
        self.lineEdit_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.Box_fil = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Box_fil.setGeometry(QtCore.QRect(20, 140, 201, 16))
        self.Box_fil.setObjectName("Box_fil")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 200, 171, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(644, 520, 101, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 10, 271, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.N_columna = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.N_columna.setGeometry(QtCore.QRect(410, 40, 271, 21))
        self.N_columna.setObjectName("N_columna")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(420, 80, 261, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.N_valor = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.N_valor.setGeometry(QtCore.QRect(420, 120, 271, 21))
        self.N_valor.setObjectName("N_valor")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 250, 781, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        Col_fil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Col_fil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Col_fil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Col_fil)
        self.statusbar.setObjectName("statusbar")
        Col_fil.setStatusBar(self.statusbar)

        self.retranslateUi(Col_fil)
        QtCore.QMetaObject.connectSlotsByName(Col_fil)

    def retranslateUi(self, Col_fil):
        _translate = QtCore.QCoreApplication.translate
        Col_fil.setWindowTitle(_translate("Col_fil", "Columnas_filas"))
        self.lineEdit.setText(_translate("Col_fil", "Desde que columna desea que se vuelvan filas"))
        self.lineEdit_2.setText(_translate("Col_fil", "Filtrar Valor"))
        self.R_si.setText(_translate("Col_fil", "Si"))
        self.R_no.setText(_translate("Col_fil", "No"))
        self.lineEdit_3.setText(_translate("Col_fil", "Valor a filtrar"))
        self.pushButton.setText(_translate("Col_fil", "Previsualizar"))
        self.pushButton_2.setText(_translate("Col_fil", "Continuar --->"))
        self.lineEdit_4.setText(_translate("Col_fil", "Nombre de la columna, columnas "))
        self.lineEdit_6.setText(_translate("Col_fil", "Nombre de la columna , valor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Col_fil = QtWidgets.QMainWindow()
    ui = Ui_Col_fil()
    ui.setupUi(Col_fil)
    Col_fil.show()
    sys.exit(app.exec())
