# Form implementation generated from reading ui file 'D:\GUI de filtrar\QT_Designer\macro.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Macro(object):
    def setupUi(self, Macro):
        Macro.setObjectName("Macro")
        Macro.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Macro)
        self.centralwidget.setObjectName("centralwidget")
        self.B_abrir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.B_abrir.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.B_abrir.setObjectName("B_abrir")
        self.Lista_excel = QtWidgets.QListWidget(parent=self.centralwidget)
        self.Lista_excel.setGeometry(QtCore.QRect(10, 130, 271, 231))
        self.Lista_excel.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.Lista_excel.setObjectName("Lista_excel")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 70, 151, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 90, 161, 31))
        self.label_2.setObjectName("label_2")
        self.Lista_estado = QtWidgets.QListWidget(parent=self.centralwidget)
        self.Lista_estado.setGeometry(QtCore.QRect(510, 130, 131, 231))
        self.Lista_estado.setStyleSheet("color: rgb(170, 255, 127);\n"
"color: rgb(0, 255, 127);")
        self.Lista_estado.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.Lista_estado.setObjectName("Lista_estado")
        self.B_ejecutar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.B_ejecutar.setGeometry(QtCore.QRect(330, 450, 151, 31))
        self.B_ejecutar.setObjectName("B_ejecutar")
        self.B_continuar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.B_continuar.setGeometry(QtCore.QRect(610, 520, 151, 31))
        self.B_continuar.setObjectName("B_continuar")
        Macro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Macro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Macro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Macro)
        self.statusbar.setObjectName("statusbar")
        Macro.setStatusBar(self.statusbar)

        self.retranslateUi(Macro)
        QtCore.QMetaObject.connectSlotsByName(Macro)

    def retranslateUi(self, Macro):
        _translate = QtCore.QCoreApplication.translate
        Macro.setWindowTitle(_translate("Macro", "Macro"))
        self.B_abrir.setText(_translate("Macro", "Abrir Achivos "))
        self.label.setText(_translate("Macro", "Exceles importados"))
        self.label_2.setText(_translate("Macro", "Estado del Excel"))
        self.B_ejecutar.setText(_translate("Macro", "Ejecutar"))
        self.B_continuar.setText(_translate("Macro", "Continuar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Macro = QtWidgets.QMainWindow()
    ui = Ui_Macro()
    ui.setupUi(Macro)
    Macro.show()
    sys.exit(app.exec())
