# Form implementation generated from reading ui file 'D:\GUI de filtrar\QT_Designer\Seleccionar_Hoja.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Importar_Archivo(object):
    def setupUi(self, Importar_Archivo):
        Importar_Archivo.setObjectName("Importar_Archivo")
        Importar_Archivo.resize(848, 110)
        self.Archivo = QtWidgets.QWidget(parent=Importar_Archivo)
        self.Archivo.setObjectName("Archivo")
        self.Caja_Archivo = QtWidgets.QComboBox(parent=self.Archivo)
        self.Caja_Archivo.setGeometry(QtCore.QRect(180, 20, 120, 20))
        self.Caja_Archivo.setStyleSheet("font: 8pt \"Algerian\";\n"
"")
        self.Caja_Archivo.setEditable(False)
        self.Caja_Archivo.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.Caja_Archivo.setObjectName("Caja_Archivo")
        self.Caja_Archivo.addItem("")
        self.Boton_conti = QtWidgets.QPushButton(parent=self.Archivo)
        self.Boton_conti.setGeometry(QtCore.QRect(680, 10, 151, 31))
        self.Boton_conti.setObjectName("Boton_conti")
        self.Boton_insert = QtWidgets.QPushButton(parent=self.Archivo)
        self.Boton_insert.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.Boton_insert.setObjectName("Boton_insert")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.Archivo)
        self.lineEdit.setGeometry(QtCore.QRect(10, 80, 361, 16))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.Archivo)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 50, 121, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.B_guardar = QtWidgets.QPushButton(parent=self.Archivo)
        self.B_guardar.setGeometry(QtCore.QRect(430, 10, 151, 31))
        self.B_guardar.setObjectName("B_guardar")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.Archivo)
        self.lineEdit_3.setGeometry(QtCore.QRect(430, 50, 141, 20))
        self.lineEdit_3.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.Archivo)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 80, 361, 16))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        Importar_Archivo.setCentralWidget(self.Archivo)

        self.retranslateUi(Importar_Archivo)
        QtCore.QMetaObject.connectSlotsByName(Importar_Archivo)

    def retranslateUi(self, Importar_Archivo):
        _translate = QtCore.QCoreApplication.translate
        Importar_Archivo.setWindowTitle(_translate("Importar_Archivo", "MainWindow"))
        self.Caja_Archivo.setCurrentText(_translate("Importar_Archivo", "Seleccione Hoja"))
        self.Caja_Archivo.setItemText(0, _translate("Importar_Archivo", "Seleccione Hoja"))
        self.Boton_conti.setText(_translate("Importar_Archivo", "Continuar  --->"))
        self.Boton_insert.setText(_translate("Importar_Archivo", "Abrir Archivo"))
        self.lineEdit_2.setText(_translate("Importar_Archivo", "Ruta del archivo abierto"))
        self.B_guardar.setText(_translate("Importar_Archivo", "Guardar Archivo"))
        self.lineEdit_3.setText(_translate("Importar_Archivo", "Ruta del archivo Guardado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Importar_Archivo = QtWidgets.QMainWindow()
    ui = Ui_Importar_Archivo()
    ui.setupUi(Importar_Archivo)
    Importar_Archivo.show()
    sys.exit(app.exec())
