# Form implementation generated from reading ui file 'D:\GUI de filtrar\QT_Designer\Seleccionar_Hoja.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Importar_Archivo(object):
    def setupUi(self, Importar_Archivo):
        Importar_Archivo.setObjectName("Importar_Archivo")
        Importar_Archivo.resize(570, 88)
        self.Archivo = QtWidgets.QWidget(parent=Importar_Archivo)
        self.Archivo.setObjectName("Archivo")
        self.Caja_Archivo = QtWidgets.QComboBox(parent=self.Archivo)
        self.Caja_Archivo.setGeometry(QtCore.QRect(190, 10, 201, 31))
        self.Caja_Archivo.setStyleSheet("font: 8pt \"Algerian\";\n"
"")
        self.Caja_Archivo.setEditable(False)
        self.Caja_Archivo.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.Caja_Archivo.setObjectName("Caja_Archivo")
        self.Caja_Archivo.addItem("")
        self.Boton_conti = QtWidgets.QPushButton(parent=self.Archivo)
        self.Boton_conti.setGeometry(QtCore.QRect(410, 10, 151, 31))
        self.Boton_conti.setObjectName("Boton_conti")
        self.Boton_insert = QtWidgets.QPushButton(parent=self.Archivo)
        self.Boton_insert.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.Boton_insert.setObjectName("Boton_insert")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.Archivo)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 531, 16))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        Importar_Archivo.setCentralWidget(self.Archivo)

        self.retranslateUi(Importar_Archivo)
        QtCore.QMetaObject.connectSlotsByName(Importar_Archivo)

    def retranslateUi(self, Importar_Archivo):
        _translate = QtCore.QCoreApplication.translate
        Importar_Archivo.setWindowTitle(_translate("Importar_Archivo", "MainWindow"))
        self.Caja_Archivo.setCurrentText(_translate("Importar_Archivo", "Seleccione Hoja"))
        self.Caja_Archivo.setItemText(0, _translate("Importar_Archivo", "Seleccione Hoja"))
        self.Boton_conti.setText(_translate("Importar_Archivo", "Continuar  --->"))
        self.Boton_insert.setText(_translate("Importar_Archivo", "Abrir Archivo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Importar_Archivo = QtWidgets.QMainWindow()
    ui = Ui_Importar_Archivo()
    ui.setupUi(Importar_Archivo)
    Importar_Archivo.show()
    sys.exit(app.exec())
